### ISSUE TITLE
"BottomBarDoubleBullet" Cannot compute the rotation matrix for a non-finite angle: -Infinity Failed assertion: line 1388 pos 12: 'radians.isFinite'

### ISSUE THREAD

**Issue by KunalTayal** [tuannvm2109/bottom_bar_matu#1]
This issue occurs in new flutter versions (3.3.9 and 3.3.10), but it is perfectly working in flutter 3.0.2 version. The relevant error-causing widget was "BottomBarDoubleBullet" as the issue with angle of rotation when it function return 0 Degree angle.

![issue](https://user-images.githubusercontent.com/76695156/208369324-7a075a71-6786-4304-a4a0-d5daf7b5bb85.PNG)

**Comment by tuannvm2109** [comment]
Thank you for your report, this issue have been fixed in version `1.3.0`
