### ISSUE TITLE
"onSelect" method is waiting for animation to trigger page change

### ISSUE THREAD

**Issue by LwinMaungMaungDev** [tuannvm2109/bottom_bar_matu#3]
When pressing tabs, the bubbles animation is played. Only after that the "onSelect" method is triggered which then we can write code to navigate pages. Although it's a small duration, some users might see a delay. I think it would be great if we can configure the animation duration or if the "onSelect" method is not waiting for the animation to finish.

**Comment by tuannvm2109** [comment]
Thank you for your feedback, this actually caused some delays for the user experience. I already fixed it in version 1.4.0.
